name: Get Repository Name 

on: [push]

jobs:
  print-repo-name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print repository name
        run: echo "Repository name is ${GITHUB_REPOSITORY##*/}"