name: test workflow
on:
    workflow_dispatch:
    push:
        branches:
            main

jobs:
    check-layer:
        runs-on: ubuntu-22.04
        steps:

            - name: checkout
              uses: actions/checkout@v4

            - name: check changes in subdirectory
              shell: bash
              run: |
                file_changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
                echo "Files changes: $file_changed"

                if [[ $file_changed == *"docs/terraform/"* ]]; then
                    directories_changed=$(echo "$file_changed" | grep -oE "docs/terraform/[^/]+" | sort -u )
                    echo "Directories changed: $directories_changed"

                    if [[ $(echo "$directories_changed" | wc -l ) -gt 1 ]]; then
                        echo "Multiple directories changed. Existing..."
                    fi

                    export LAYER_NAME=$(echo "$directories_changed" | cut -d'/' -f3)
                    echo "Layer name: $LAYER_NAME"

                else
                    echo "No changes in doc/terrform/ directory. skil==pping layer check"
                fi







