name: test workflow
on:
    workflow_dispatch:
    push:
        branches:
            main

jobs:
    check-layer:
        runs-on: ubuntu-22.04
        steps:

            - name: checkout
              uses: actions/checkout@v4

            - name: check changes in subdirectory
              run:
                ./.github/scripts/check-layer.sh






