name: test workflow
on:
    workflow_dispatch:
    push:
        branches:
            main

jobs:
    check-layer:
        runs-on: ubuntu-22.04
        steps:

            - name: checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: check changes in subdirectory
              shell: bash
              env:
                EVENT_BEFORE: ${{ github.event.before }}
                GIT_SHA: ${{ github.sha }}
              run: |
                echo "Start"
                file_changed=$(git diff --name-only $EVENT_BEFORE $GIT_SHA)
                echo "Files changes: $file_changed"

                if [[ $file_changed == *"docs/terrform/"* ]]; then
                    directories_changed=$(echo "$file_changed" | grep -oP "docs/terrform/\K[^/]*" | sort -u | paste -sd, -)
                    echo "Directories changed: $directories_changed"

                    if [[ $(echo "$directories_changed" | wc -l ) -gt 1 ]]; then
                        echo "Multiple directories changed. Existing..."
                    fi

                    export LAYER_NAME=$(echo "$directories_changed" | cut -d'/' -f3)
                    echo "Layer name: $LAYER_NAME"

                else
                    echo "No changes in doc/terrform/ directory. skil==pping layer check"
                fi







